service: ${self:custom.ingest-schema-repo.name}

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-finch
  - serverless-python-requirements

custom:
  ingest-schema-repo: ${file(ingest-schema-repo.yml)}
  snsTopicName: ${self:custom.ingest-schema-repo.name}-${self:custom.ingest-schema-repo.notification-event}
  client:
    bucketName: ${self:custom.ingest-schema-repo.bucket-name}
    distributionFolder: client

provider:
  name: aws
  region: eu-west-1
  environment:
    BUCKET: ${self:custom.ingest-schema-repo.bucket-name}
    API_KEY: ${self:custom.ingest-schema-repo.api-key}
    TOPIC_NAME: ${self:custom.snsTopicName}
    TOPIC_ARN:  { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.snsTopicName}" ] ]  }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.ingest-schema-repo.bucket-name}/*"
    - Effect: Allow
      Action:
       - "sns:Publish"
      Resource:
       - "Ref" : "Notification"

functions:
  onGithubRelease:
    runtime: python3.6
    handler: handler.on_github_release
    events:
      - http:
          path: github/release
          method: post

resources:
  Resources:
    Notification:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.snsTopicName}