service: ingest-schema-repo

frameworkVersion: ">=1.0.0 <2.0.0"

plugins:
  - serverless-finch
  - serverless-python-requirements

custom:
  ingest-schema-repo: ${file(ingest-schema-repo.yml)}
  client:
    bucketName: ${self:custom.ingest-schema-repo.bucket-name}
    distributionFolder: client

provider:
  name: aws
  region: eu-west-1
  environment:
    BUCKET: ${self:custom.ingest-schema-repo.bucket-name}
    API_KEY: ${self:custom.ingest-schema-repo.api-key}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.ingest-schema-repo.bucket-name}/*"

functions:
  onGithubReleaseJS:
    runtime: nodejs6.10
    handler: handler.onGithubRelease
    events:
      - http:
          path: github/release_js
          method: post
  onGithubRelease:
    runtime: python3.6
    handler: handler.on_github_release
    events:
      - http:
          path: github/release
          method: post