service: ingest-schema-repo

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

functions:
  onGithubEvent:
    handler: handler.onGithubEvent
    events:
      - sns: github-event
